version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: car-booking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 8877
      MYSQL_DATABASE: car_booking
      MYSQL_USER: booking_user
      MYSQL_PASSWORD: booking_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: car-booking-api
    ports:
      - "8083:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/car_booking
      SPRING_DATASOURCE_USERNAME: booking_user
      SPRING_DATASOURCE_PASSWORD: booking_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
